export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  
  LEADS_VIEW: 'leads.view',
  LEADS_CREATE: 'leads.create',
  LEADS_UPDATE: 'leads.update',
  LEADS_DELETE: 'leads.delete',
  LEADS_ASSIGN: 'leads.assign',
  
  CONTACTS_VIEW: 'contacts.view',
  CONTACTS_CREATE: 'contacts.create',
  CONTACTS_UPDATE: 'contacts.update',
  CONTACTS_DELETE: 'contacts.delete',
  
  COMPANIES_VIEW: 'companies.view',
  COMPANIES_CREATE: 'companies.create',
  COMPANIES_UPDATE: 'companies.update',
  COMPANIES_DELETE: 'companies.delete',
  
  DEALS_VIEW: 'deals.view',
  DEALS_CREATE: 'deals.create',
  DEALS_UPDATE: 'deals.update',
  DEALS_DELETE: 'deals.delete',
  
  PIPELINE_VIEW: 'pipeline.view',
  PIPELINE_MANAGE: 'pipeline.manage',
  
  ACTIVITIES_VIEW: 'activities.view',
  ACTIVITIES_CREATE: 'activities.create',
  ACTIVITIES_UPDATE: 'activities.update',
  ACTIVITIES_DELETE: 'activities.delete',
  
  TASKS_VIEW: 'tasks.view',
  TASKS_CREATE: 'tasks.create',
  TASKS_UPDATE: 'tasks.update',
  TASKS_DELETE: 'tasks.delete',
  
  BUSINESS_FINDER_SEARCH: 'business_finder.search',
  BUSINESS_FINDER_IMPORT: 'business_finder.import',
  
  REPORTS_VIEW: 'reports.view',
  
  USERS_VIEW: 'users.view',
  USERS_MANAGE: 'users.manage',
  
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',
  
  AUDIT_LOGS_VIEW: 'audit_logs.view',

  AI_VIEW: 'ai.view',
  AI_USE: 'ai.use',
  AI_MANAGE: 'ai.manage',
  
  COMMUNICATIONS_VIEW: 'communications.view',
  COMMUNICATIONS_SEND: 'communications.send',
  COMMUNICATIONS_MANAGE: 'communications.manage',
  
  WORKFLOWS_VIEW: 'workflows.view',
  WORKFLOWS_CREATE: 'workflows.create',
  WORKFLOWS_MANAGE: 'workflows.manage',
  
  SEQUENCES_VIEW: 'sequences.view',
  SEQUENCES_CREATE: 'sequences.create',
  SEQUENCES_MANAGE: 'sequences.manage',
  
  ENRICHMENT_USE: 'enrichment.use',
  
  BILLING_VIEW: 'billing.view',
  BILLING_MANAGE: 'billing.manage',
  
  MODULES_MANAGE: 'modules.manage',
} as const;

export type PermissionCode = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  Owner: Object.values(PERMISSIONS),
  Admin: Object.values(PERMISSIONS).filter(p => p !== PERMISSIONS.BILLING_MANAGE && p !== PERMISSIONS.MODULES_MANAGE),
  'Sales Manager': [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_UPDATE,
    PERMISSIONS.LEADS_DELETE,
    PERMISSIONS.LEADS_ASSIGN,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_CREATE,
    PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.CONTACTS_DELETE,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.COMPANIES_CREATE,
    PERMISSIONS.COMPANIES_UPDATE,
    PERMISSIONS.COMPANIES_DELETE,
    PERMISSIONS.DEALS_VIEW,
    PERMISSIONS.DEALS_CREATE,
    PERMISSIONS.DEALS_UPDATE,
    PERMISSIONS.DEALS_DELETE,
    PERMISSIONS.PIPELINE_VIEW,
    PERMISSIONS.PIPELINE_MANAGE,
    PERMISSIONS.ACTIVITIES_VIEW,
    PERMISSIONS.ACTIVITIES_CREATE,
    PERMISSIONS.ACTIVITIES_UPDATE,
    PERMISSIONS.ACTIVITIES_DELETE,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_DELETE,
    PERMISSIONS.BUSINESS_FINDER_SEARCH,
    PERMISSIONS.BUSINESS_FINDER_IMPORT,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_USE,
    PERMISSIONS.COMMUNICATIONS_VIEW,
    PERMISSIONS.COMMUNICATIONS_SEND,
    PERMISSIONS.COMMUNICATIONS_MANAGE,
    PERMISSIONS.WORKFLOWS_VIEW,
    PERMISSIONS.WORKFLOWS_CREATE,
    PERMISSIONS.SEQUENCES_VIEW,
    PERMISSIONS.SEQUENCES_CREATE,
    PERMISSIONS.ENRICHMENT_USE,
  ],
  'Sales Representative': [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_UPDATE,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_CREATE,
    PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.COMPANIES_CREATE,
    PERMISSIONS.COMPANIES_UPDATE,
    PERMISSIONS.DEALS_VIEW,
    PERMISSIONS.DEALS_CREATE,
    PERMISSIONS.DEALS_UPDATE,
    PERMISSIONS.PIPELINE_VIEW,
    PERMISSIONS.ACTIVITIES_VIEW,
    PERMISSIONS.ACTIVITIES_CREATE,
    PERMISSIONS.ACTIVITIES_UPDATE,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.BUSINESS_FINDER_SEARCH,
    PERMISSIONS.BUSINESS_FINDER_IMPORT,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.AI_VIEW,
    PERMISSIONS.AI_USE,
    PERMISSIONS.COMMUNICATIONS_VIEW,
    PERMISSIONS.COMMUNICATIONS_SEND,
    PERMISSIONS.SEQUENCES_VIEW,
    PERMISSIONS.ENRICHMENT_USE,
  ],
};

export function hasPermission(userPermissions: string[], requiredPermission: PermissionCode): boolean {
  return userPermissions.includes(requiredPermission);
}
